name: remote ssh command
on:
  push:
    branches:
      - beta

env:
  GMAIL_APP: ${{ secrets.GMAIL_APP }}
  SERVER_NAME: ${{ secrets.SERVER_NAME }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd devloweb
          git pull
          sudo systemctl restart devloweb.service
          echo "OK"
