name: remote ssh command
on:
  push:
    branches:
      - beta

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GMAIL_APP: ${{ secrets.GMAIL_APP }}
      SERVER_NAME: ${{ secrets.SERVER_NAME }}
      ENV: ${{ secrets.ENV }}
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          export GMAIL_APP="${{secrets.GMAIL_APP}}"
          export SERVER_NAME=${{secrets.SERVER_NAME}}
          export ENV=${{secrets.ENV}}
          export DB_USERNAME=${{secrets.DB_USERNAME}}
          export DB_PASSWORD=${{secrets.DB_PASSWORD}}
          cd devloweb
          git pull
          sudo systemctl restart devloweb.service
          env
