name: run pytest
on:
  push:
    branches:
      - beta


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: run les tests
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: '100m'
        script: |
          set -e
          cd devlotest/devloweb
          git pull
          export PYTHONPATH=/home/deploy/devloweb/devlovenv/bin/pytest App/tests/test_inscription.py -v --runslow 
          env
