name: remote ssh command
on:
  push:
    branches:
      - test_env

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          export GMAIL_APP=${{ secrets.GMAIL_APP }}
          export SERVER_NAME=${{ secrets.SERVER_NAME }}
          export ENV=${{ secrets.ENV }}
          cd devloweb
          git pull
          sudo systemctl restart devloweb.service
          env
