name: remote ssh command
on:
  push:
    branches:
      - beta

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: run les tests
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          set -e
          cd devlotest/devloweb
          git pull
          export PYTHONPATH=/home/timtonix/devlotest/devloweb/
          devlovenv/bin/python/pytest App/tests/test_inscription.py --runslow
          env
